---
- name: Greeting and Backup Playbook
  hosts: awx-demo.local
  tasks:
    - name: Create Backup Directory
      file:
        path: "/data/projects/backup"
        state: directory

    - name: Create Greeting File
      copy:
        content: "Hello, welcome to AWX!"
        dest: "/data/projects/backup/greeting.txt"
